version: '3'

services:
    php:
        container_name: "php-fpm"
        build:
            context: ./docker/php
        volumes:
            - .:/var/www
        networks:
            - stack

    nginx:
        container_name: "nginx"
        build:
            context: ./docker/nginx
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        ports:
            - "8181:80"
        networks:
            - stack

    postgres:
        container_name: "postgres"
        image: postgres:${POSTGRES_VERSION:-13}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
            POSTGRES_USER: ${POSTGRES_USER:-symfony}
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            -  "5442:5432"
        networks:
            - stack

    node:
        container_name: "node"
        build:
            context: ./docker/node
        volumes:
            - .:/app

    composer:
        container_name: "composer"
        image: composer:2
        volumes:
            -   .:/app

volumes:
    db-data:

networks:
    stack:
